galaxy_info:
  author: IBM
  description: Role to export federation metadata
  company: IBM

  license: Apache

  min_ansible_version: 2.8

  galaxy_tags:
  - isam
  - ibm
  - export
  - metadata
  - federation

dependencies:
  - ibm.isam.common_handlers