---
#ansible_user: admin
#ansible_password: "{{ vault_ansible_password }}"
vault_ansible_password: admin
#First steps
ansible_connection: "ibm.isam.isam"
ansible_isam_username: admin@local
ansible_isam_password: "{{ vault_ansible_password }}"
ansible_isam_port: 443
ansible_host: "{{ inventory_hostname }}"

# 906 Activation keys
activation_module_code_wga_906: "<codes>"
activation_module_code_mga_906: "<codes>"
activation_module_code_federation_906: "<codes>"

# Enter your activation keys here 10
activation_module_code_wga_10: <codes>
activation_module_code_mga_10: <codes>
activation_module_code_federation_10: <codes>

activation_keys:
 - id: wga
   code: "{{ activation_module_code_wga_10 }}"
 - id: mga
   code: "{{ activation_module_code_mga_10 }}"
 - id: federation
   code: "{{ activation_module_code_federation_10 }}"

#time
time_cfg:
  enableNtp: true
  ntpServers: "pool.ntp.org"
  timeZone: "Europe/Brussels"
