---
#{"user_registry":"local","ps_mode":"local","ps_mode_radio":"on","registry":"on",
#TODO : new : "local_interface_only":"false"
#"admin_pwd":"Passw0rd","admin_pwd_confirm":"Passw0rd","admin_cert_lifetime":1460,"ssl_compliance":"none"}

admin_id: sec_master
admin_pwd: "{{ vault_sec_master_pwd }}"

policyserver_runtime:
  configuration:
    admin_pwd: "{{ vault_sec_master_pwd }}"
    ps_mode: local
    user_registry: local
    ldap_pwd: "{{ vault_ldap_pwd }}"